/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const RunsLazyRouteImport = createFileRoute('/runs')()

const RunsLazyRoute = RunsLazyRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/runs.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/runs': typeof RunsLazyRoute
}
export interface FileRoutesByTo {
  '/runs': typeof RunsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/runs': typeof RunsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/runs'
  fileRoutesByTo: FileRoutesByTo
  to: '/runs'
  id: '__root__' | '/runs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RunsLazyRoute: typeof RunsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  RunsLazyRoute: RunsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
